### ISSUE TITLE
3.16 support

### ISSUE THREAD

**Issue by varemenos** [pgaubatz/gnome-shell-extension-pitch-dark#2]
Please add Gnome 3.16 support as many distros already use it

**Comment by pgaubatz** [comment]
Hi,

unfortunately I'm still on 3.14 (currently using Debian Jessie), so I can't test if it still works on 3.16.
Can you try...
1. manually copying the `pitch-dark@patrick.gaubatz.at/` directory from the repository to `~/.local/share/gnome-shell/extensions/`
2. and changing line 6 from `"shell-version": [ "3.12", "3.14" ],` to `"shell-version": [ "3.12", "3.14", "3.16" ],` in the `~/.local/share/gnome-shell/extensions/pitch-dark@patrick.gaubatz.at/metadata.json` file? 

Thanks, I'm looking forward to hearing from you... :)

Cheers,
Patrick

**Comment by pgaubatz** [comment]
So... without having actually tested the extension on 3.16, I'm closing the ticket (for now)...

**Comment by varemenos** [comment]
I've tested it, it works fine for gtk2 apps. For the gtk3 ones all you have to do is enable it from the tweak tool

**Comment by pgaubatz** [comment]
Thanks for testing! I've already uploaded a new version to https://extensions.gnome.org/
